name: Build ğŸ¥–ğŸ˜­ğŸŒ­

on:
  workflow_dispatch: {}
  schedule:
    # åˆ† æ™‚ æ—¥ æœˆ æ˜ŸæœŸå¹¾
    - cron: '0 4 * * 1,3,5'

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      # æŸ¥çœ‹repo
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          lfs: true # ä½¿ç”¨ LFS

      # (å¯é¸) Cacheå¯ä»¥è®“ä½ ä¹‹å¾ŒBuildæ›´å¿«
      - name: Cache
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # ç”¨Game-CI Builderå»ºç½®å°ˆæ¡ˆ
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64

      # è¼¸å‡ºæˆartifact
      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build
          retention-days: 2     # å¹¾å¤©å¾Œæœƒåˆªé™¤ï¼Œé€™é‚Šæ˜¯å…©å¤©
